# -*- coding: utf-8 -*-
"""run_predict.py

Automatically generated by Colab.
"""

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pandas_datareader.data as web
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
import warnings
warnings.filterwarnings('ignore')


# ==========================================
# 1. เตรียมข้อมูล & สร้างเป้าหมายแบบทายส่วนต่าง (Delta)
# ==========================================
print("1. Loading data and creating features...")
symbol = "GC=F"
# ขยับปีเริ่มต้นเป็น 2022 เพื่อตัดความผันผวนช่วงโควิดออก ให้โมเดลโฟกัสเทรนด์ล่าสุด
start_date = "2022-01-01"
split_ratio = 0.80 # เพิ่มสัดส่วน Train Set เป็น 80%

df_gold = yf.download(symbol, start=start_date, auto_adjust=True)
if isinstance(df_gold.columns, pd.MultiIndex):
    df_gold.columns = df_gold.columns.get_level_values(0)
df_gold = df_gold[["Open", "High", "Low", "Close", "Volume"]].copy()

df_dxy = yf.download("DX-Y.NYB", start=start_date, auto_adjust=True)[['Close']].rename(columns={'Close': 'DXY'})
if isinstance(df_dxy.columns, pd.MultiIndex):
    df_dxy.columns = df_dxy.columns.get_level_values(0)

end_date = datetime.today().strftime('%Y-%m-%d')
df_cpi = web.DataReader('CPIAUCSL', 'fred', start_date, end_date)
df_cpi.index.name = 'Date'
df_cpi = df_cpi.rename(columns={'CPIAUCSL': 'CPI'})

df = df_gold.join([df_dxy, df_cpi], how='left').ffill().bfill().reset_index()
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date").reset_index(drop=True)

# Technical Indicators
df["Close_lag_1"] = df["Close"].shift(1)
df["Close_lag_3"] = df["Close"].shift(3)

# ⭐️ หัวใจสำคัญ: สร้าง Target เป็น "ส่วนต่างราคา" (Delta)
df["Target_Delta"] = df["Close"] - df["Close_lag_1"]

df["MA_5"] = df["Close"].rolling(5).mean()
df["MA_10"] = df["Close"].rolling(10).mean()
df["Return"] = df["Close"].pct_change()

delta = df['Close'].diff()
gain = (delta.where(delta > 0, 0)).ewm(alpha=1/14, adjust=False).mean()
loss = (-delta.where(delta < 0, 0)).ewm(alpha=1/14, adjust=False).mean()
df['RSI_14'] = 100 - (100 / (1 + (gain / loss)))

ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
ema_26 = df['Close'].ewm(span=26, adjust=False).mean()
df['MACD'] = ema_12 - ema_26
df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()

df['DayOfWeek'] = df['Date'].dt.dayofweek
df['Month'] = df['Date'].dt.month

df = df.dropna().reset_index(drop=True)

feature_cols = [
    'Open', 'High', 'Low', 'Volume', 'Close_lag_1', 'Close_lag_3',
    'MA_5', 'MA_10', 'Return', 'RSI_14', 'MACD', 'MACD_Signal',
    'DayOfWeek', 'Month', 'DXY', 'CPI'
]

train_size = int(len(df) * split_ratio)
df_train = df.iloc[:train_size].copy()
df_test = df.iloc[train_size:].copy()

# ==========================================
# 2. เทรนโมเดล MLP (ปรับสเกลด้วย StandardScaler)
# ==========================================
print("2. Training MLP model...")
# ใช้ StandardScaler จะเหมาะกับข้อมูลประเภท % เปลี่ยนแปลงและผลต่าง มากกว่า MinMaxScaler
scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(df_train[feature_cols])
X_test_scaled = scaler_X.transform(df_test[feature_cols])

# ทายผลเป็น Target_Delta
y_train = df_train['Target_Delta'].values

# ขยายเลเยอร์ให้ลึกขึ้นเพื่อจับรูปแบบความผันผวนย่อยๆ
mlp_model = MLPRegressor(
    hidden_layer_sizes=(256, 128, 64),
    activation='relu',
    solver='adam',
    alpha=0.01, # ป้องกัน Overfitting
    batch_size=32,
    learning_rate='adaptive',
    max_iter=2000,
    early_stopping=True, # หยุดเทรนอัตโนมัติถ้าโมเดลเริ่มตัน
    random_state=42
)
mlp_model.fit(X_train_scaled, y_train)

# พยากรณ์ "ส่วนต่างราคา"
y_pred_delta = mlp_model.predict(X_test_scaled)

# ⭐️ แปลงส่วนต่างกลับเป็นราคาจริง (ราคาเมื่อวาน + ส่วนต่างที่ทายได้)
y_pred_real_price = df_test['Close_lag_1'].values + y_pred_delta

print("\n=== MLP Model Results ===")
print(f"MAE: {mean_absolute_error(df_test['Close'], y_pred_real_price):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(df_test['Close'], y_pred_real_price)):.2f}")
print(f"R-Squared (R2): {r2_score(df_test['Close'], y_pred_real_price):.4f}")

# ==========================================
# 3. พยากรณ์ล่วงหน้า 5 วัน (Forecast)
# ==========================================
print("\n3. Forecasting next 5 days...")
last_row = df.iloc[-1].copy()
future_dates = pd.bdate_range(start=last_row['Date'] + timedelta(days=1), periods=5)

future_preds = []
current_features = last_row[feature_cols].copy()
current_close = last_row['Close']

for i in range(5):
    curr_X = scaler_X.transform(current_features.values.reshape(1, -1))
    pred_delta = mlp_model.predict(curr_X)[0]

    # คำนวณราคาของวันรุ่งขึ้น
    pred_real = current_close + pred_delta
    future_preds.append(pred_real)

    # อัปเดตค่าเพื่อวนลูปวันถัดไป
    current_features['Close_lag_1'] = pred_real
    current_features['MA_5'] = (current_features['MA_5'] * 4 + pred_real) / 5
    current_close = pred_real

df_future = pd.DataFrame({
    'Date': future_dates,
    'Close': [np.nan] * 5,
    'Predicted': future_preds
})

results = df_test[['Date', 'Close']].copy()
results['Predicted'] = y_pred_real_price
final_csv = pd.concat([results, df_future], ignore_index=True)

final_csv['Date'] = final_csv['Date'].dt.strftime('%Y-%m-%d')

# บันทึกไฟล์ลงโฟลเดอร์ data
file_name = "data/gold_prediction_final_dashboard.csv"
final_csv.to_csv(file_name, index=False)
print(f"\nSaved file '{file_name}' successfully!")